//circle.js v1.0.2
if(typeof html5jp=='undefined'){html5jp=new Object();}
if(typeof html5jp.graph=='undefined'){html5jp.graph=new Object();}
html5jp.graph.circle=function(id){var elm=document.getElementById(id);if(!elm){return;}
if(!elm.nodeName.match(/^CANVAS$/i)){return;}
if(!elm.parentNode.nodeName.match(/^DIV$/i)){return;};if(!elm.getContext){return;}
this.canvas=elm;this.ctx=this.canvas.getContext('2d');this.canvas.style.margin="0";this.canvas.parentNode.style.position="relative";this.canvas.parentNode.style.padding="0";this.canvas.parentNode.style.width=this.canvas.width+"px";this.canvas.parentNode.style.height=this.canvas.height+"px";};html5jp.graph.circle.prototype.draw=function(items,inparams){if(!this.ctx){return;}
var params={backgroundColor:null,shadow:true,border:false,caption:false,captionNum:true,captionRate:true,fontSize:"12px",fontFamily:"Arial,sans-serif",textShadow:true,captionColor:"#ffffff",startAngle:-90,legend:true,legendFontSize:"12px",legendFontFamily:"Arial,sans-serif",legendColor:"#000000",otherCaption:"other"};if(inparams&&typeof(inparams)=='object'){for(var key in inparams){params[key]=inparams[key];}}
this.params=params;if(params.backgroundColor){this.ctx.beginPath();this.ctx.fillStyle=params.backgroundColor;this.ctx.fillRect(0,0,this.canvas.width,this.canvas.height);}
if(this.canvas.width/this.canvas.height<1.5||this.canvas.height<200){params.legend==false;}
var canvas_pos=this._getElementAbsPos(this.canvas);var cpos={x:this.canvas.width/2,y:this.canvas.height/2,r:Math.min(this.canvas.width,this.canvas.height)*0.8/2};items=this._fold_items(items);var item_num=items.length;if(params.legend==true){cpos.x=this.canvas.height*0.1+cpos.r;var tmpdiv=document.createElement('DIV');tmpdiv.appendChild(document.createTextNode('TEST'));tmpdiv.style.fontSize=params.legendFontSize;tmpdiv.style.fontFamily=params.legendFontFamily;tmpdiv.style.color=params.legendColor;tmpdiv.style.margin="0";tmpdiv.style.padding="0";tmpdiv.style.visible="hidden";tmpdiv.style.position="absolute";tmpdiv.style.left=canvas_pos.x.toString()+"px";tmpdiv.style.top=canvas_pos.y.toString()+"px";this.canvas.parentNode.appendChild(tmpdiv);var lpos={x:this.canvas.height*0.2+cpos.r*2,y:(this.canvas.height-(tmpdiv.offsetHeight*item_num+tmpdiv.offsetHeight*0.2*(item_num-1)))/2,h:tmpdiv.offsetHeight};lpos.cx=lpos.x+lpos.h*1.4;lpos.cw=this.canvas.width-lpos.cx;tmpdiv.parentNode.removeChild(tmpdiv);}
if(params.shadow==true){this._make_shadow(cpos);}
this.ctx.beginPath();this.ctx.arc(cpos.x,cpos.y,cpos.r,0,Math.PI*2,false)
this.ctx.closePath();this.ctx.fillStyle="black";this.ctx.fill();var sum=0;for(var i=0;i<item_num;i++){var n=items[i][1];if(isNaN(n)||n<0){throw new Error('invalid graph item data.'+n);}
sum+=n;}
if(sum<=0){throw new Error('invalid graph item data.');}
var colors=["24,41,206","198,0,148","214,0,0","255,156,0","33,156,0","33,41,107","115,0,90","132,0,0","165,99,0","24,123,0"];var rates=new Array();var startAngle=this._degree2radian(params.startAngle);for(var i=0;i<item_num;i++){var cap=items[i][0];var n=items[i][1];var r=n/sum;var p=Math.round(r*1000)/10;var rad=this._degree2radian(360*r);endAngle=startAngle+rad;var rgb=colors[i];var rgbo=this._csscolor2rgb(items[i][2]);if(rgbo){rgb=rgbo.r+","+rgbo.g+","+rgbo.b;}
if(n>0){this.ctx.beginPath();if(p>=100){this.ctx.arc(cpos.x,cpos.y,cpos.r,0,Math.PI*2,false);}else{this.ctx.moveTo(cpos.x,cpos.y);this.ctx.lineTo(cpos.x+cpos.r*Math.cos(startAngle),cpos.y+cpos.r*Math.sin(startAngle));this.ctx.arc(cpos.x,cpos.y,cpos.r,startAngle,endAngle,false);}
this.ctx.closePath();var radgrad=this.ctx.createRadialGradient(cpos.x,cpos.y,0,cpos.x,cpos.y,cpos.r);radgrad.addColorStop(0,"rgba("+rgb+",1)");radgrad.addColorStop(0.7,"rgba("+rgb+",0.85)");radgrad.addColorStop(1,"rgba("+rgb+",0.75)");this.ctx.fillStyle=radgrad;this.ctx.fill();if(params.border==true){this.ctx.stroke();}
var drate;var fontSize;if(r<=0.03){drate=1.1;}else if(r<=0.05){drate=0.9;}else if(r<=0.1){drate=0.8;}else if(r<=0.15){drate=0.7;}else{drate=0.6;}
var cp={x:cpos.x+(cpos.r*drate)*Math.cos((startAngle+endAngle)/2),y:cpos.y+(cpos.r*drate)*Math.sin((startAngle+endAngle)/2)};var div=document.createElement('DIV');if(r<=0.05){if(params.captionRate==true){div.appendChild(document.createTextNode(p+"%"));}}else{if(params.caption==true){div.appendChild(document.createTextNode(cap));if(params.captionNum==true||params.captionRate==true){div.appendChild(document.createElement('BR'));}}
if(params.captionRate==true){div.appendChild(document.createTextNode(p+"%"));}
if(params.captionNum==true){var numCap=n;if(params.caption==true||params.captionRate==true){numCap="("+numCap+")";}
div.appendChild(document.createTextNode(numCap));}}
div.style.position='absolute';div.style.textAlign='center';div.style.color=params.captionColor;div.style.fontSize=params.fontSize;div.style.fontFamily=params.fontFamily;div.style.margin="0";div.style.padding="0";div.style.visible="hidden";if(params.textShadow==true){var dif=[[0,1],[0,-1],[1,0],[1,1],[1,-1],[-1,0],[-1,1],[-1,-1]];for(var j=0;j<8;j++){var s=div.cloneNode(true);this.canvas.parentNode.appendChild(s);s.style.color="black";s.style.left=(parseFloat(cp.x-s.offsetWidth/2+dif[j][0])).toString()+"px";s.style.top=(cp.y-s.offsetHeight/2+dif[j][1]).toString()+"px";}}
this.canvas.parentNode.appendChild(div);div.style.left=(cp.x-div.offsetWidth/2).toString()+"px";div.style.top=(cp.y-div.offsetHeight/2).toString()+"px";}
if(params.legend==true){var ltxt=document.createElement('DIV');ltxt.appendChild(document.createTextNode(cap));ltxt.style.position="absolute";ltxt.style.fontSize=params.legendFontSize;ltxt.style.fontFamily=params.legendFontFamily;ltxt.style.color=params.legendColor;ltxt.style.margin="0";ltxt.style.padding="0";ltxt.style.left=lpos.cx.toString()+"px";ltxt.style.top=lpos.y.toString()+"px";ltxt.style.width=(lpos.cw).toString()+"px";ltxt.style.whiteSpace="nowrap";ltxt.style.overflow="hidden";this.canvas.parentNode.appendChild(ltxt);if(params.shadow==true){this.ctx.beginPath();this.ctx.rect(lpos.x+1,lpos.y+1,lpos.h,lpos.h);this.ctx.fillStyle="#222222";this.ctx.fill();}
this.ctx.beginPath();this.ctx.rect(lpos.x,lpos.y,lpos.h,lpos.h);this.ctx.fillStyle="black";this.ctx.fill();this.ctx.beginPath();this.ctx.rect(lpos.x,lpos.y,lpos.h,lpos.h);var symbolr={x:lpos.x+lpos.h/2,y:lpos.y+lpos.h/2,r:Math.sqrt(lpos.h*lpos.h*2)/2};var legend_radgrad=this.ctx.createRadialGradient(symbolr.x,symbolr.y,0,symbolr.x,symbolr.y,symbolr.r);legend_radgrad.addColorStop(0,"rgba("+rgb+",1)");legend_radgrad.addColorStop(0.7,"rgba("+rgb+",0.85)");legend_radgrad.addColorStop(1,"rgba("+rgb+",0.75)");this.ctx.fillStyle=legend_radgrad;this.ctx.fill();lpos.y=lpos.y+lpos.h*1.2;}
startAngle=endAngle;}};html5jp.graph.circle.prototype._fold_items=function(items){var len=items.length;if(len<=10){return items;}
var n=0;for(var i=9;i<len;i++){n+=items[i][1];}
var newitems=items.slice(0,10);newitems[9]=[this.params.otherCaption,n];return newitems;};html5jp.graph.circle.prototype._getElementAbsPos=function(elm){var obj=new Object();obj.x=elm.offsetLeft;obj.y=elm.offsetTop;while(elm.offsetParent){elm=elm.offsetParent;obj.x+=elm.offsetLeft;obj.y+=elm.offsetTop;}
return obj;};html5jp.graph.circle.prototype._make_shadow=function(cpos){this.ctx.beginPath();this.ctx.arc(cpos.x+5,cpos.y+5,cpos.r,0,Math.PI*2,false)
this.ctx.closePath();var radgrad=this.ctx.createRadialGradient(cpos.x+5,cpos.y+5,0,cpos.x+5,cpos.y+5,cpos.r);if(document.uniqueID){radgrad.addColorStop(0,'#555555');}else{radgrad.addColorStop(0,'rgba(0,0,0,1)');radgrad.addColorStop(0.93,'rgba(0,0,0,1)');radgrad.addColorStop(1,'rgba(0,0,0,0)');}
this.ctx.fillStyle=radgrad;this.ctx.fill();};html5jp.graph.circle.prototype._degree2radian=function(degree){return(Math.PI/180)*degree;};html5jp.graph.circle.prototype._csscolor2rgb=function(c){if(!c){return null;}
var color_map={black:"#000000",gray:"#808080",silver:"#c0c0c0",white:"#ffffff",maroon:"#800000",red:"#ff0000",purple:"#800080",fuchsia:"#ff00ff",green:"#008000",lime:"#00FF00",olive:"#808000",yellow:"#FFFF00",navy:"#000080",blue:"#0000FF",teal:"#008080",aqua:"#00FFFF"};c=c.toLowerCase();var o=new Object();if(c.match(/^[a-zA-Z]+$/)&&color_map[c]){c=color_map[c];}
var m=null;if(m=c.match(/^\#([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i)){o.r=parseInt(m[1],16);o.g=parseInt(m[2],16);o.b=parseInt(m[3],16);}else if(m=c.match(/^\#([a-f\d]{1})([a-f\d]{1})([a-f\d]{1})$/i)){o.r=parseInt(m[1]+"0",16);o.g=parseInt(m[2]+"0",16);o.b=parseInt(m[3]+"0",16);}else if(m=c.match(/^rgba*\(\s*(\d+),\s*(\d+),\s*(\d+)/i)){o.r=m[1];o.g=m[2];o.b=m[3];}else if(m=c.match(/^rgba*\(\s*(\d+)\%,\s*(\d+)\%,\s*(\d+)\%/i)){o.r=Math.round(m[1]*255/100);o.g=Math.round(m[2]*255/100);o.b=Math.round(m[3]*255/100);}else{return null;}
return o;};


//line.js v1.0.2
if(typeof html5jp=='undefined'){html5jp=new Object();}
if(typeof html5jp.graph=='undefined'){html5jp.graph=new Object();}
html5jp.graph.line=function(id){var elm=document.getElementById(id);if(!elm){return;}
if(!elm.nodeName.match(/^CANVAS$/i)){return;}
if(!elm.parentNode.nodeName.match(/^DIV$/i)){return;};if(!elm.getContext){return;}
this.canvas=elm;this.ctx=this.canvas.getContext('2d');this.canvas.style.margin="0";this.canvas.parentNode.style.position="relative";this.canvas.parentNode.style.padding="0";this.canvas.parentNode.style.width=this.canvas.width+"px";this.canvas.parentNode.style.height=this.canvas.height+"px";};html5jp.graph.line.prototype.draw=function(items,inparams){if(!this.ctx){return;}
var params={x:[],y:[],yMax:null,yMin:0,backgroundColor:"#ffffff",gbackgroundColor:"#dddddd",gGradation:true,lineWidth:1,dotRadius:3,dotType:"disc",hLineWidth:2,hLineType:"dotted",hLineColor:"#aaaaaa",xAxisWidth:2,xAxisColor:"#000000",yAxisWidth:2,yAxisColor:"#000000",xScaleColor:"#000000",xScaleFontSize:"10px",xScaleFontFamily:"Arial,sans-serif",yScaleColor:"#000000",yScaleFontSize:"10px",yScaleFontFamily:"Arial,sans-serif",xCaptionColor:"#000000",xCaptionFontSize:"12px",xCaptionFontFamily:"Arial,sans-serif",yCaptionColor:"#000000",yCaptionFontSize:"12px",yCaptionFontFamily:"Arial,sans-serif",dLabel:true,dLabelColor:"#000000",dLabelFontSize:"10px",dLabelFontFamily:"Arial,sans-serif",legend:true,legendFontSize:"12px",legendFontFamily:"Arial,sans-serif",legendColor:"#000000"};if(inparams&&typeof(inparams)=='object'){for(var key in inparams){params[key]=inparams[key];}}
this.params=params;if(params.backgroundColor){this.ctx.beginPath();this.ctx.fillStyle=params.backgroundColor;this.ctx.fillRect(0,0,this.canvas.width,this.canvas.height);}
if(this.canvas.width/this.canvas.height<1.5||this.canvas.height<200){params.legend==false;}
var canvas_pos=this._getElementAbsPos(this.canvas);var cpos={x0:this.canvas.width*0.1,y0:this.canvas.height*0.9,x1:this.canvas.width*0.9,y1:this.canvas.height*0.1};if(typeof(params.x)=="object"&&params.x.length>0){cpos.y0=this.canvas.height*0.8;}
if(typeof(params.y)=="object"&&params.y.length>0){cpos.x0=this.canvas.width*0.15;cpos.y1=this.canvas.height*0.15}
if(params.legend==true){cpos.x1=this.canvas.width*0.7;}
cpos.w=cpos.x1-cpos.x0;cpos.h=cpos.y0-cpos.y1;var item_num=items.length;if(item_num>10){item_num=10;}
if(params.legend==true){var legend_tmp_s=this._getTextBoxSize('TEST',params.legendFontSize,params.legendFontFamily);var lpos={x:Math.round(cpos.x1+this.canvas.width*0.03),y:Math.round((this.canvas.height-(legend_tmp_s.h*item_num+legend_tmp_s.h*0.2*(item_num-1)))/2),h:legend_tmp_s.h};lpos.cx=lpos.x+Math.round(lpos.h*2.5);lpos.cw=this.canvas.width-lpos.cx;}
if(params.gGradation==true){this.ctx.beginPath();this.ctx.moveTo(cpos.x0,cpos.y0);this.ctx.lineTo(cpos.x1,cpos.y0);this.ctx.lineTo(cpos.x1,cpos.y1);this.ctx.lineTo(cpos.x0,cpos.y1);this.ctx.closePath();var radgrad=this.ctx.createLinearGradient(cpos.x0,cpos.y1,cpos.x0,cpos.y0);var o_gbc=this._csscolor2rgb(params.gbackgroundColor);var gbc=o_gbc.r+","+o_gbc.g+","+o_gbc.b;radgrad.addColorStop(0,"rgb("+gbc+")");radgrad.addColorStop(1,"rgb(255,255,255)");this.ctx.fillStyle=radgrad;this.ctx.fill();}else{this.ctx.fillStyle=params.gbackgroundColor;this.ctx.fillRect(cpos.x0,cpos.y1,cpos.w,cpos.h);}
var max_v=null;var min_v=null;var max_n=0;if(params.y.length>1){max=params.y[params.y.length-1];}
for(var i=0;i<item_num;i++){var n=items[i].length;if(n<2){continue;}
for(var j=1;j<n;j++){var v=items[i][j];if(isNaN(v)){throw new Error('invalid graph item data.'+n);}
if(max_v==null){max_v=v;}else if(v>=max_v){max_v=v;}
if(min_v==null){min_v=v;}else if(v<=min_v){min_v=v;}}
if(n-1>=max_n){max_n=n-1;}}
if(typeof(params.yMin)!="number"){params.yMin=0;}
if(typeof(params.yMax)!="number"){params.yMax=max_v+Math.abs(max_v-min_v)*0.1;}
var v_range=Math.abs(params.yMax-params.yMin);if(typeof(params.hLineWidth)=="number"&&params.hLineWidth>0){var h_line_type="dashed";if(params.hLineType.match(/^(solid|dashed|dotted)$/i)){h_line_type=params.hLineType;}
for(var i=1;i<params.y.length;i++){var aline_x0=cpos.x0;var aline_y0=Math.round(cpos.y0-cpos.h*(params.y[i]-params.yMin)/v_range);var aline_x1=cpos.x1;this._draw_h_aline(aline_x0,aline_y0,aline_x1,params.hLineWidth,h_line_type,params.hLineColor);}}
var colors=["24,41,206","198,0,148","214,0,0","255,156,0","33,156,0","33,41,107","115,0,90","132,0,0","165,99,0","24,123,0"];var plots=new Array();for(var i=0;i<item_num;i++){this.ctx.beginPath();this.ctx.lineJoin="round";plots[i]=new Array();var n=items[i].length;for(var j=1;j<n;j++){var v=items[i][j];var p={x:Math.round(cpos.x0+cpos.w*(j-0.5)/max_n),y:Math.round(cpos.y0-cpos.h*(v-params.yMin)/v_range),v:v}
plots[i].push(p);if(j==1){this.ctx.moveTo(p.x,p.y);}else{this.ctx.lineTo(p.x,p.y);}}
var line_width=1;if(typeof(params.lineWidth)=="object"&&!isNaN(params.lineWidth[i])){line_width=params.lineWidth[i];}else if(typeof(params.lineWidth)=="number"&&!isNaN(params.lineWidth)){line_width=params.lineWidth;}
this.ctx.lineWidth=line_width;var line_color="rgb("+colors[i]+")";this.ctx.strokeStyle=line_color;this.ctx.stroke();var dot_rad=null;if(typeof(params.dotRadius)=="object"&&!isNaN(params.dotRadius[i])&&params.dotRadius[i]>0){dot_rad=params.dotRadius[i];}else if(typeof(params.dotRadius)=="number"&&!isNaN(params.dotRadius)&&params.dotRadius>0){dot_rad=params.dotRadius;}
var dot_type=null;if(typeof(params.dotType)=="object"&&typeof(params.dotType[i])=="string"){dot_type=params.dotType[i];}else if(typeof(params.dotType)=="string"){dot_type=params.dotType;}else{dot_type="disc";}
if(dot_rad>0){for(var k=0;k<plots[i].length;k++){this._draw_dot(plots[i][k].x,plots[i][k].y,dot_rad,dot_type,colors[i]);}}
if(params.dLabel==true){for(var k=0;k<plots[i].length;k++){if(plots[i][k].x<cpos.x0||plots[i][k].x>cpos.x1||plots[i][k].y>cpos.y0||plots[i][k].y<cpos.y1){continue;}
var dlabel=plots[i][k].v.toString();var margin=1;if(dot_rad!=null&&dot_rad>0){margin+=dot_rad;}
var s=this._getTextBoxSize(dlabel,params.dLabelFontSize,params.dLabelFontFamily);var dlabel_x=plots[i][k].x-Math.round(s.w/2);var dlabel_y=plots[i][k].y-Math.round(s.h)-margin;this._drawText(dlabel_x,dlabel_y,dlabel,params.dLabelFontSize,params.dLabelFontFamily,params.dLabelColor);}}
if(params.legend==true){this._drawText(lpos.cx,lpos.y,items[i][0],params.legendFontSize,params.legendFontFamily,params.legendColor);this._draw_h_aline(lpos.x,Math.round(lpos.y+lpos.h/2),lpos.x+lpos.h*2,line_width,"solid",line_color);if(dot_rad>0){this._draw_dot(Math.round(lpos.x+lpos.h),Math.round(lpos.y+lpos.h/2),dot_rad,dot_type,colors[i]);}
lpos.y=lpos.y+lpos.h*1.2;}}
this.ctx.fillStyle=params.backgroundColor;this.ctx.fillRect(cpos.x0,0,cpos.w,cpos.y1);this.ctx.fillRect(cpos.x0,cpos.y0,cpos.w,this.canvas.height-cpos.y0);if(typeof(params.xAxisWidth)=="number"&&params.xAxisWidth>0){this._draw_h_aline(cpos.x0,cpos.y0,cpos.x1,params.xAxisWidth,"solid",params.xAxisColor);}
if(typeof(params.yAxisWidth)=="number"&&params.yAxisWidth>0){this._draw_v_aline(cpos.x0,cpos.y0,cpos.y1,params.yAxisWidth,"solid",params.yAxisColor);}
var xscale_y_under=0;for(var i=1;i<=max_n;i++){if(typeof(params.x[i])!="string"){continue;}
if(params.x[i]==""){continue;}
var s=this._getTextBoxSize(params.x[i],params.xScaleFontSize,params.xScaleFontFamily);var xscale_x=Math.round(cpos.x0+cpos.w*(i-0.5)/max_n)-Math.round(s.w/2);var xscale_y=cpos.y0+5;this._drawText(xscale_x,xscale_y,params.x[i],params.xScaleFontSize,params.xScaleFontFamily,params.xScaleColor);if(xscale_y+s.h>=xscale_y_under){xscale_y_under=xscale_y+s.h;}}
var yscale_y_top=this.canvas.height;for(var i=1;i<params.y.length;i++){if(typeof(params.y[i])!="number"){continue;}
var v=params.y[i].toString();if(v==""){continue;}
if(params.y[i]<params.yMin||params.y[i]>params.yMax){continue;}
var s=this._getTextBoxSize(v,params.yScaleFontSize,params.yScaleFontFamily);var yscale_y=Math.round(cpos.y0-cpos.h*(params.y[i]-params.yMin)/v_range)-Math.round(s.h/2);var yscale_x=Math.round(cpos.x0-s.w)-5;this._drawText(yscale_x,yscale_y,v,params.yScaleFontSize,params.yScaleFontFamily,params.yScaleColor);if(yscale_y<=yscale_y_top){yscale_y_top=yscale_y;}}
if(typeof(params.x[0])=="string"&&params.x[0]!=""){var s=this._getTextBoxSize(params.x[0],params.xCaptionFontSize,params.xCaptionFontFamily);var xcaption_y=cpos.y0+5;if(xscale_y_under>0){xcaption_y=xscale_y_under+5;}
var xcaption_x=Math.round(cpos.x0+(cpos.w/2)-(s.w/2));this._drawText(xcaption_x,xcaption_y,params.x[0],params.xCaptionFontSize,params.xCaptionFontFamily,params.xCaptionColor);}
if(typeof(params.y[0])=="string"&&params.y[0]!=""){var s=this._getTextBoxSize(params.y[0],params.yCaptionFontSize,params.yCaptionFontFamily);var ycaption_y=yscale_y_top-s.h-5;if(yscale_y_top>cpos.y1){ycaption_y=cpos.y1-s.h-5;}
var ycaption_x=Math.round(cpos.x0-(s.w/2));if(ycaption_x<5){ycaption_x=5;}
this._drawText(ycaption_x,ycaption_y,params.y[0],params.yCaptionFontSize,params.yCaptionFontFamily,params.yCaptionColor);}};html5jp.graph.line.prototype._draw_v_aline=function(x0,y0,y1,width,type,color){color=this._csscolor2rgb(color);this.ctx.beginPath();color="rgb("+color.r+","+color.g+","+color.b+")"
this.ctx.strokeStyle=color;this.ctx.lineWidth=width;if(type=="solid"){this.ctx.moveTo(x0,y0);this.ctx.lineTo(x0,y1);this.ctx.stroke();}else if(type=="dashed"||(type=="dotted"&&width<2)){var y=y0;while(1){if(y-width*4<y1){break;}
this.ctx.moveTo(x0,y);y=y-width*4;this.ctx.lineTo(x0,y);this.ctx.stroke();if(y-width*2<y1){break;}
y=y-width*2;}}else if(type=="dotted"){this.ctx.fillStyle=color;var y=y0;while(1){if(y-width*2<y1){break;}
this.ctx.arc(x0,y,width/2,0,Math.PI*2,false);this.ctx.fill();if(y-width*2<y1){break;}
y=y-width*2;}}};html5jp.graph.line.prototype._draw_h_aline=function(x0,y0,x1,width,type,color){color=this._csscolor2rgb(color);this.ctx.beginPath();color="rgb("+color.r+","+color.g+","+color.b+")"
this.ctx.strokeStyle=color;this.ctx.lineWidth=width;if(type=="solid"){this.ctx.moveTo(x0,y0);this.ctx.lineTo(x1,y0);this.ctx.stroke();}else if(type=="dashed"||(type=="dotted"&&width<2)){var x=x0;while(1){if(x+width*4>x1){break;}
this.ctx.moveTo(x,y0);x=x+width*4;this.ctx.lineTo(x,y0);this.ctx.stroke();if(x+width*2>x1){break;}
x=x+width*2;}}else if(type=="dotted"){this.ctx.fillStyle=color;var x=x0;while(1){if(x+width*2>x1){break;}
this.ctx.arc(x,y0,width/2,0,Math.PI*2,false);this.ctx.fill();if(x+width*2>x1){break;}
x=x+width*2;}}};html5jp.graph.line.prototype._draw_dot=function(x,y,rad,type,color){this.ctx.beginPath();this.ctx.fillStyle="rgb("+color+")";if(type=="disc"){this.ctx.arc(x,y,rad,0,Math.PI*2,false);}else if(type=="square"){this.ctx.moveTo(x-rad,y-rad);this.ctx.lineTo(x+rad,y-rad);this.ctx.lineTo(x+rad,y+rad);this.ctx.lineTo(x-rad,y+rad);}else if(type=="triangle"){this.ctx.moveTo(x,y-rad);this.ctx.lineTo(x+rad,y+rad);this.ctx.lineTo(x-rad,y+rad);}else if(type=="i-triangle"){this.ctx.moveTo(x,y+rad);this.ctx.lineTo(x+rad,y-rad);this.ctx.lineTo(x-rad,y-rad);}else if(type=="diamond"){this.ctx.moveTo(x,y-rad);this.ctx.lineTo(x+rad,y);this.ctx.lineTo(x,y+rad);this.ctx.lineTo(x-rad,y);}else{this.ctx.arc(x,y,rad,0,Math.PI*2,false);}
this.ctx.closePath();this.ctx.fill();};html5jp.graph.line.prototype._drawText=function(x,y,text,font_size,font_family,color){var div=document.createElement('DIV');div.appendChild(document.createTextNode(text));div.style.fontSize=font_size;div.style.fontFamily=font_family;div.style.color=color;div.style.margin="0";div.style.padding="0";div.style.position="absolute";div.style.left=x.toString()+"px";div.style.top=y.toString()+"px";this.canvas.parentNode.appendChild(div);}
html5jp.graph.line.prototype._getTextBoxSize=function(text,font_size,font_family){var tmpdiv=document.createElement('DIV');tmpdiv.appendChild(document.createTextNode(text));tmpdiv.style.fontSize=font_size;tmpdiv.style.fontFamily=font_family;tmpdiv.style.margin="0";tmpdiv.style.padding="0";tmpdiv.style.visible="hidden";tmpdiv.style.position="absolute";tmpdiv.style.left="0px";tmpdiv.style.top="0px";this.canvas.parentNode.appendChild(tmpdiv);var o={w:tmpdiv.offsetWidth,h:tmpdiv.offsetHeight};tmpdiv.parentNode.removeChild(tmpdiv);return o;}
html5jp.graph.line.prototype._getElementAbsPos=function(elm){var obj=new Object();obj.x=elm.offsetLeft;obj.y=elm.offsetTop;while(elm.offsetParent){elm=elm.offsetParent;obj.x+=elm.offsetLeft;obj.y+=elm.offsetTop;}
return obj;};html5jp.graph.line.prototype._csscolor2rgb=function(c){if(!c){return null;}
var color_map={black:"#000000",gray:"#808080",silver:"#c0c0c0",white:"#ffffff",maroon:"#800000",red:"#ff0000",purple:"#800080",fuchsia:"#ff00ff",green:"#008000",lime:"#00FF00",olive:"#808000",yellow:"#FFFF00",navy:"#000080",blue:"#0000FF",teal:"#008080",aqua:"#00FFFF"};c=c.toLowerCase();var o=new Object();if(c.match(/^[a-zA-Z]+$/)&&color_map[c]){c=color_map[c];}
var m=null;if(m=c.match(/^\#([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i)){o.r=parseInt(m[1],16);o.g=parseInt(m[2],16);o.b=parseInt(m[3],16);}else if(m=c.match(/^\#([a-f\d]{1})([a-f\d]{1})([a-f\d]{1})$/i)){o.r=parseInt(m[1]+"0",16);o.g=parseInt(m[2]+"0",16);o.b=parseInt(m[3]+"0",16);}else if(m=c.match(/^rgba*\(\s*(\d+),\s*(\d+),\s*(\d+)/i)){o.r=m[1];o.g=m[2];o.b=m[3];}else if(m=c.match(/^rgba*\(\s*(\d+)\%,\s*(\d+)\%,\s*(\d+)\%/i)){o.r=Math.round(m[1]*255/100);o.g=Math.round(m[2]*255/100);o.b=Math.round(m[3]*255/100);}else{return null;}
return o;};


//vbar.js v1.0.4
if(typeof html5jp=='undefined'){html5jp=new Object();}
if(typeof html5jp.graph=='undefined'){html5jp.graph=new Object();}
html5jp.graph.vbar=function(id){var elm=document.getElementById(id);if(!elm){return;}
if(!elm.nodeName.match(/^CANVAS$/i)){return;}
if(!elm.parentNode.nodeName.match(/^DIV$/i)){return;};if(!elm.getContext){return;}
this.canvas=elm;this.ctx=this.canvas.getContext('2d');this.canvas.style.margin="0";this.canvas.parentNode.style.position="relative";this.canvas.parentNode.style.padding="0";this.canvas.parentNode.style.width=this.canvas.width+"px";this.canvas.parentNode.style.height=this.canvas.height+"px";};html5jp.graph.vbar.prototype.draw=function(items,inparams){if(!this.ctx){return;}
this._reset();this.items=items;var params={x:[],y:[],yMax:null,yMin:0,backgroundColor:"#ffffff",gBackgroundColor:"#dddddd",gGradation:true,barShape:"square",barColors:null,_barColors:["rgb(24,41,206)","rgb(198,0,148)","rgb(214,0,0)","rgb(255,156,0)","rgb(33,156,0)","rgb(33,41,107)","rgb(115,0,90)","rgb(132,0,0)","rgb(165,99,0)","rgb(24,123,0)"],barGradation:true,barAlpha:0.7,borderAlpha:0.2,xAxisWidth:1,xAxisColor:"#aaaaaa",yAxisWidth:1,yAxisColor:"#aaaaaa",xScale:true,xScaleColor:"#000000",xScaleFontSize:"10px",xScaleFontFamily:"Arial,sans-serif",yScale:true,yScaleColor:"#000000",yScaleFontSize:"10px",yScaleFontFamily:"Arial,sans-serif",xCaptionColor:"#000000",xCaptionFontSize:"12px",xCaptionFontFamily:"Arial,sans-serif",yCaptionColor:"#000000",yCaptionFontSize:"12px",yCaptionFontFamily:"Arial,sans-serif",aLineWidth:1,aLineAlpha:0.2,dLabel:true,dLabelColor:"#000000",dLabelFontSize:"10px",dLabelFontFamily:"Arial,sans-serif",legend:true,legendFontSize:"12px",legendFontFamily:"Arial,sans-serif",legendColor:"#000000"};if(inparams&&typeof(inparams)=='object'){for(var key in inparams){if(key.match(/^_/)){continue;}
params[key]=inparams[key];}}
if(params.barColors!=null&&params.barColors.length>0){for(var i=0;i<params._barColors.length;i++){var c=params.barColors[i];var co=this._csscolor2rgb(c);if(co==null){params.barColors[i]=params._barColors[i];}else{params.barColors[i]=c;}}}else{params.barColors=params._barColors;}
this.params=params;if(this.canvas.width/this.canvas.height<1.5||this.canvas.height<200){params.legend==false;}
var item_num=items.length;if(item_num>10){item_num=10;}
var max_n=0;for(var i=0;i<item_num;i++){var n=items[i].length;if(n<2){continue;}
if(n-1>=max_n){max_n=n-1;}}
params.max_n=max_n;if(max_n==0){throw new Error('no graph item data.'+n);}
var max_v=0;for(var i=1;i<=max_n;i++){var n=items.length;var sum=0;for(var j=0;j<n;j++){var v=items[j][i];if(isNaN(v)||v<0){throw new Error('invalid graph item data.'+n);}
sum+=v;}
if(sum>=max_v){max_v=sum;}}
if(typeof(params.yMin)!="number"){params.yMin=0;}
if(typeof(params.yMax)!="number"){params.yMax=max_v*1.1}else if(params.yMax<=max_v){params.yMax=max_v;}
if(params.y.length<2){params.aLinePositions=this._aline_positions_auto_calc(params.yMin,params.yMax);}else{params.aLinePositions=params.y.slice(1);}
var cpos={x0:this.canvas.width*0.05,y0:this.canvas.height*0.95,x1:this.canvas.width*0.95,y1:this.canvas.height*0.05};if(params.legend==true){cpos.x1=this.canvas.width*0.7;}
if(params.x.length>0){var x_caption_text_size=this._getTextBoxSize("a",params.xCaptionFontSize,params.xCaptionFontFamily);cpos.y0-=x_caption_text_size.h*1.5;cpos.x_caption_y=cpos.y0+x_caption_text_size.h/2;}
if(params.xScale==true||params.x.length>1){var x_scale_text_size=this._getTextBoxSize("a",params.xScaleFontSize,params.xScaleFontFamily);cpos.y0-=x_scale_text_size.h*1.5;cpos.x_scale_y=cpos.y0+x_scale_text_size.h*0.7;}
if(params.y.length>0){var y_caption_text_size=this._getTextBoxSize("a",params.yCaptionFontSize,params.yCaptionFontFamily);cpos.y1+=y_caption_text_size.h*1.5;cpos.y_caption_y=cpos.y1-y_caption_text_size.h*1.5;}
if(params.yScale==true||params.y.length>1){var y_scale_text_size=this._getTextBoxSize(params.aLinePositions[params.aLinePositions.length-1].toString(),params.yScaleFontSize,params.yScaleFontFamily);cpos.x0+=y_scale_text_size.w*1.1;}
cpos.w=cpos.x1-cpos.x0;cpos.h=cpos.y0-cpos.y1;if(params.barShape=="square"){cpos.r=0.6*cpos.w/max_n/2;}else{cpos.r=0.7*cpos.w/max_n/2;}
if(cpos.r<5&&cpos.r>=3){params.barShape="line";}
params.cpos=cpos;this.params=params;this._draw_canvas_background();this._draw_graph_background();var x_scale_positions=new Array();var d_labels=new Array();for(var i=1;i<=max_n;i++){var sum=0;var x=cpos.x0+(i-0.5)*(cpos.w/max_n);x_scale_positions.push(x);for(var j=0;j<items.length;j++){var v=items[j][i];var y=cpos.y0;if(params.yMax>0){y=cpos.y0-sum*cpos.h/params.yMax;}
var h=0;if(params.yMax>0){h=v*cpos.h/params.yMax;}
if(params.barShape=="line"){this._draw_vertical_bar_line(this.ctx,x,y,h,cpos.r,params.barColors[j],params.barAlpha);}else if(params.barShape=="flat"){this._draw_vertical_bar_flat(this.ctx,x,y,h,cpos.r,params.barColors[j],params.barAlpha,params.borderAlpha,params.barGradation);}else if(params.barShape=="square"){this._draw_vertical_bar_square(this.ctx,x,y,h,cpos.r,cpos.r/3,params.barColors[j],params.barAlpha,params.borderAlpha,params.barGradation);}else if(params.barShape=="cylinder"){this._draw_vertical_bar_cylinder(this.ctx,x,y,h,cpos.r,cpos.r/3,params.barColors[j],params.barAlpha,params.borderAlpha,params.barGradation);}
sum+=v;}
d_labels.push({x:x,v:sum});}
this._draw_data_label(d_labels);this._draw_x_scale_label(x_scale_positions);this._draw_y_scale_label();this._draw_legend();};html5jp.graph.vbar.prototype._reset=function(){var parent=this.canvas.parentNode;var num=parent.childNodes.length;for(var i=num-1;i>=0;i--){var nd=parent.childNodes.item(i);if(/^canvas$/i.test(nd.nodeName)){continue;}
parent.removeChild(nd);}
this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);};html5jp.graph.vbar.prototype._draw_data_label=function(labels){var p=this.params;if(p.dLabel!=true){return;}
var n=labels.length;var pos=new Array();var max_w=0;for(var i=0;i<n;i++){var text=labels[i].v.toString();var s=this._getTextBoxSize(text,p.dLabelFontSize,p.dLabelFontFamily);max_w=Math.max(s.w,max_w);var dx=labels[i].x-s.w/2;var dy=p.cpos.y0-s.h*1.3;if(p.yMax>0){dy=p.cpos.y0-labels[i].v*p.cpos.h/p.yMax-s.h*1.3;}
pos.push({x:dx,y:dy,text:text});}
if(max_w<p.cpos.w/n){for(var i=0;i<n;i++){this._drawText(pos[i].x,pos[i].y,pos[i].text,p.dLabelFontSize,p.dLabelFontFamily,p.dLabelColor);}}};html5jp.graph.vbar.prototype._draw_legend=function(){var p=this.params;if(p.legend!=true){return;}
var s=this._getTextBoxSize('TEST',p.legendFontSize,p.legendFontFamily);var item_num=this.items.length;var lpos={x:Math.round(p.cpos.x1+this.canvas.width*0.05),y:Math.round((this.canvas.height-(s.h*item_num+s.h*0.2*(item_num-1)))/2),h:s.h};lpos.cx=lpos.x+Math.round(lpos.h*1.5);lpos.cw=this.canvas.width-lpos.cx;for(var i=0;i<item_num;i++){this._drawText(lpos.cx,lpos.y,this.items[i][0],p.legendFontSize,p.legendFontFamily,p.legendColor);this.ctx.save();this._make_path_legend_mark(lpos.x,lpos.y,s.h,s.h);this.ctx.fillStyle=p.gBackgroundColor;this.ctx.fill();this.ctx.restore();this.ctx.save();this._make_path_legend_mark(lpos.x,lpos.y,s.h,s.h);this.ctx.fillStyle=p.barColors[i];this.ctx.globalAlpha=p.barAlpha;this.ctx.fill();this.ctx.restore();this.ctx.save();this._make_path_legend_mark(lpos.x,lpos.y,s.h,s.h);this.ctx.strokeStyle=p.barColors[i];this.ctx.globalAlpha=p.borderAlpha;this.ctx.stroke();this.ctx.restore();if(p.barGradation==true){this.ctx.save();this._make_path_legend_mark(lpos.x,lpos.y,s.h,s.h);var grad=this.ctx.createLinearGradient(lpos.x,lpos.y,lpos.x+s.h,lpos.y+s.h);grad.addColorStop(0,"rgba(0, 0, 0, 0.1)");grad.addColorStop(0.3,"rgba(255, 255, 255, 0.1)");grad.addColorStop(1,"rgba(0, 0, 0, 0.4)");this.ctx.fillStyle=grad;this.ctx.fill();this.ctx.restore();}
lpos.y=lpos.y+lpos.h*1.2;}};html5jp.graph.vbar.prototype._make_path_legend_mark=function(x,y,w,h){this.ctx.beginPath();this.ctx.moveTo(x,y);this.ctx.lineTo(x+w,y);this.ctx.lineTo(x+w,y+h);this.ctx.lineTo(x,y+h);this.ctx.closePath();};html5jp.graph.vbar.prototype._aline_positions_auto_calc=function(min,max){var range=max-min;var power10=Math.floor(Math.log(range)/Math.log(10));var unit=Math.pow(10,power10);if((Math.log(range)/Math.log(10))%1==0){unit=unit/10;}
var keta_age=1;if(unit<1){keta_age+=Math.abs(power10);}
var p=Math.pow(10,keta_age);range=range*p;unit=unit*p;min=min*p;max=max*p;var array=[min];var unum=range/unit;if(unum>5){unit=unit*2;}else if(unum<=2){unit=unit*3/10}
var i=1;while(min+unit*i<=max){array.push(min+unit*i);i++;}
for(var i=0;i<array.length;i++){array[i]=array[i]/p;}
return array;};html5jp.graph.vbar.prototype._draw_y_scale_label=function(pos){var p=this.params;if(p.y.length>0){var text=p.y[0].toString();if(text!=""){var s=this._getTextBoxSize(text,p.yCaptionFontSize,p.yCaptionFontFamily);var x=p.cpos.x0-s.w/2;if(x<this.canvas.width*0.05){x=this.canvas.width*0.05;}
this._drawText(x,p.cpos.y_caption_y,text,p.yCaptionFontSize,p.yCaptionFontFamily,p.yCaptionColor);}}
if(p.yScale==true&&p.aLinePositions.length>0){for(var i=0;i<p.aLinePositions.length;i++){var v=p.aLinePositions[i];if(isNaN(v)){continue;}
if(v>p.yMax){continue;}
var text=v.toString();var s=this._getTextBoxSize(text,p.yScaleFontSize,p.yScaleFontFamily);var x=p.cpos.x0-p.cpos.r/2-s.w*1.1;var y=p.cpos.y0-s.h/2;if(p.yMax-p.yMin>0){y=p.cpos.y0-v*p.cpos.h/(p.yMax-p.yMin)-s.h/2;}
if(p.barShape=="cylinder"||p.barShape=="square"){var d=p.cpos.r/3;y+=d;}
this._drawText(x,y,text,p.yScaleFontSize,p.yScaleFontFamily,p.yScaleColor);}}};html5jp.graph.vbar.prototype._draw_x_scale_label=function(pos){var p=this.params;if(p.x.length>0){var text=p.x[0].toString();if(text!=""){var s=this._getTextBoxSize(text,p.xCaptionFontSize,p.xCaptionFontFamily);var x=Math.round(p.cpos.x0+p.cpos.w/2-s.w/2);this._drawText(x,p.cpos.x_caption_y,text,p.xCaptionFontSize,p.xCaptionFontFamily,p.xCaptionColor);}}
if(p.xScale==true&&p.x.length>1){for(var i=0;i<pos.length;i++){if(i+1>p.x.length-1){break;}
var text=p.x[i+1].toString();if(text==""){continue;}
var s=this._getTextBoxSize(text,p.xScaleFontSize,p.xScaleFontFamily);var x=Math.round(pos[i]-s.w/2);this._drawText(x,p.cpos.x_scale_y,text,p.xScaleFontSize,p.xScaleFontFamily,p.xScaleColor);}}};html5jp.graph.vbar.prototype._draw_graph_background=function(){var p=this.params;var d=p.cpos.r/3;if(p.barShape=="line"||p.barShape=="flat"){this._draw_graph_background_back(p.cpos.x0,p.cpos.y0,p.cpos.w,p.cpos.h);this._draw_graph_axis(p.cpos.x0,p.cpos.y0,p.cpos.w,p.cpos.h);}else{this._draw_graph_background_back(p.cpos.x0+d,p.cpos.y0-d,p.cpos.w,p.cpos.h);this.ctx.save();this.ctx.beginPath();this.ctx.moveTo(p.cpos.x0+d,p.cpos.y0-d);this.ctx.lineTo(p.cpos.x0+d+p.cpos.w,p.cpos.y0-d);this.ctx.lineTo(p.cpos.x0-d+p.cpos.w,p.cpos.y0+d);this.ctx.lineTo(p.cpos.x0-d,p.cpos.y0+d);this.ctx.closePath();this.ctx.fillStyle=p.gBackgroundColor;this.ctx.fill();this.ctx.restore();this.ctx.save();this.ctx.beginPath();this.ctx.moveTo(p.cpos.x0+d,p.cpos.y0-d);this.ctx.lineTo(p.cpos.x0+d+p.cpos.w,p.cpos.y0-d);this.ctx.lineTo(p.cpos.x0-d+p.cpos.w,p.cpos.y0+d);this.ctx.lineTo(p.cpos.x0-d,p.cpos.y0+d);this.ctx.closePath();this.ctx.fillStyle="rgba(255,255,255,0.3)";this.ctx.fill();this.ctx.restore();this.ctx.save();this.ctx.beginPath();this.ctx.moveTo(p.cpos.x0+d,p.cpos.y0-d);this.ctx.lineTo(p.cpos.x0-d,p.cpos.y0+d);this.ctx.lineTo(p.cpos.x0-d,p.cpos.y0+d-p.cpos.h);this.ctx.lineTo(p.cpos.x0+d,p.cpos.y0-d-p.cpos.h);this.ctx.closePath();this.ctx.fillStyle=p.gBackgroundColor;this.ctx.fill();this.ctx.restore();if(p.aLineWidth>0){this.ctx.save();for(var i=0;i<p.aLinePositions.length;i++){if(p.aLinePositions[i]>p.yMax){continue;}
if(p.yMax-p.yMin==0){continue;}
var aY=p.cpos.y0-p.cpos.h*p.aLinePositions[i]/(p.yMax-p.yMin);aY=Math.round(aY);this.ctx.beginPath();this.ctx.strokeStyle="rgba(0,0,0,"+p.aLineAlpha+")";this.ctx.lineWidth=p.aLineWidth;this.ctx.moveTo(p.cpos.x0+d,aY-d-p.aLineWidth/2);this.ctx.lineTo(p.cpos.x0-d,aY+d-p.aLineWidth/2);this.ctx.stroke();this.ctx.beginPath();this.ctx.strokeStyle="rgba(255,255,255,"+p.aLineAlpha+")";this.ctx.lineWidth=p.aLineWidth;this.ctx.moveTo(p.cpos.x0+d,aY-d+p.aLineWidth/2);this.ctx.lineTo(p.cpos.x0-d,aY+d+p.aLineWidth/2);this.ctx.stroke();}
this.ctx.restore();}
this.ctx.save();this.ctx.beginPath();this.ctx.moveTo(p.cpos.x0+d,p.cpos.y0-d);this.ctx.lineTo(p.cpos.x0-d,p.cpos.y0+d);this.ctx.lineTo(p.cpos.x0-d,p.cpos.y0+d-p.cpos.h);this.ctx.lineTo(p.cpos.x0+d,p.cpos.y0-d-p.cpos.h);this.ctx.closePath();this.ctx.fillStyle="rgba(0,0,0,0.1)";this.ctx.fill();this.ctx.restore();this._draw_graph_axis(p.cpos.x0-d,p.cpos.y0+d,p.cpos.w,p.cpos.h);}};html5jp.graph.vbar.prototype._draw_graph_axis=function(x,y,w,h){this.ctx.save();var p=this.params;this.ctx.beginPath();this.ctx.lineWidth=p.xAxisWidth;this.ctx.strokeStyle=p.xAxisColor;this.ctx.moveTo(x,y);this.ctx.lineTo(x+w,y);this.ctx.stroke();this.ctx.beginPath();this.ctx.lineWidth=p.yAxisWidth;this.ctx.strokeStyle=p.yAxisColor;this.ctx.moveTo(x,y);this.ctx.lineTo(x,y-h);this.ctx.stroke();this.ctx.restore();};html5jp.graph.vbar.prototype._draw_graph_background_back=function(x,y,w,h){var p=this.params;this.ctx.save();this.ctx.fillStyle=p.gBackgroundColor;this.ctx.fillRect(x,y-h,w,h);this.ctx.beginPath();this.ctx.moveTo(x,y);this.ctx.lineTo(x+w,y);this.ctx.lineTo(x+w,y-h);this.ctx.lineTo(x,y-h);this.ctx.closePath();this.ctx.fill();this.ctx.restore();if(p.gGradation==true){this.ctx.save();var grad=this.ctx.createLinearGradient(x,y-h,x+w,y);grad.addColorStop(0,"rgba(0, 0, 0, 0.1)");grad.addColorStop(0.3,"rgba(255, 255, 255, 0.2)");grad.addColorStop(1,"rgba(0, 0, 0, 0.3)");this.ctx.fillStyle=grad;this.ctx.beginPath();this.ctx.moveTo(x,y);this.ctx.lineTo(x+w,y);this.ctx.lineTo(x+w,y-h);this.ctx.lineTo(x,y-h);this.ctx.closePath();this.ctx.fill();this.ctx.restore();}
if(p.aLineWidth>0){this.ctx.save();for(var i=0;i<p.aLinePositions.length;i++){if(p.aLinePositions[i]>p.yMax){continue;}
if(p.yMax-p.yMin==0){continue;}
var aY=y-h*p.aLinePositions[i]/(p.yMax-p.yMin);aY=Math.round(aY);this.ctx.beginPath();this.ctx.strokeStyle="rgba(0,0,0,"+p.aLineAlpha+")";this.ctx.lineWidth=p.aLineWidth;this.ctx.moveTo(x,aY-p.aLineWidth/2);this.ctx.lineTo(x+w,aY-p.aLineWidth/2);this.ctx.stroke();this.ctx.beginPath();this.ctx.strokeStyle="rgba(255,255,255,"+p.aLineAlpha+")";this.ctx.lineWidth=p.aLineWidth;this.ctx.moveTo(x,aY+p.aLineWidth/2);this.ctx.lineTo(x+w,aY+p.aLineWidth/2);this.ctx.stroke();}
this.ctx.restore();}};html5jp.graph.vbar.prototype._draw_canvas_background=function(){var c=this._csscolor2rgb(this.params.backgroundColor);if(c!=null){this.ctx.save();this.ctx.beginPath();this.ctx.fillStyle=this.params.backgroundColor;this.ctx.fillRect(0,0,this.canvas.width,this.canvas.height);this.ctx.restore();}};html5jp.graph.vbar.prototype._drawText=function(x,y,text,font_size,font_family,color){var div=document.createElement('DIV');div.appendChild(document.createTextNode(text));div.style.fontSize=font_size;div.style.fontFamily=font_family;div.style.color=color;div.style.margin="0";div.style.padding="0";div.style.position="absolute";div.style.left=x.toString()+"px";div.style.top=y.toString()+"px";this.canvas.parentNode.appendChild(div);}
html5jp.graph.vbar.prototype._getTextBoxSize=function(text,font_size,font_family){var tmpdiv=document.createElement('DIV');tmpdiv.appendChild(document.createTextNode(text));tmpdiv.style.fontSize=font_size;tmpdiv.style.fontFamily=font_family;tmpdiv.style.margin="0";tmpdiv.style.padding="0";tmpdiv.style.visible="hidden";tmpdiv.style.position="absolute";tmpdiv.style.left="0px";tmpdiv.style.top="0px";this.canvas.parentNode.appendChild(tmpdiv);var o={w:tmpdiv.offsetWidth,h:tmpdiv.offsetHeight};tmpdiv.parentNode.removeChild(tmpdiv);return o;}
html5jp.graph.vbar.prototype._getElementAbsPos=function(elm){var obj=new Object();obj.x=elm.offsetLeft;obj.y=elm.offsetTop;while(elm.offsetParent){elm=elm.offsetParent;obj.x+=elm.offsetLeft;obj.y+=elm.offsetTop;}
return obj;};html5jp.graph.vbar.prototype._csscolor2rgb=function(c){if(!c){return null;}
var color_map={black:"#000000",gray:"#808080",silver:"#c0c0c0",white:"#ffffff",maroon:"#800000",red:"#ff0000",purple:"#800080",fuchsia:"#ff00ff",green:"#008000",lime:"#00FF00",olive:"#808000",yellow:"#FFFF00",navy:"#000080",blue:"#0000FF",teal:"#008080",aqua:"#00FFFF"};c=c.toLowerCase();var o=new Object();if(c.match(/^[a-zA-Z]+$/)&&color_map[c]){c=color_map[c];}
var m=null;if(m=c.match(/^\#([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i)){o.r=parseInt(m[1],16);o.g=parseInt(m[2],16);o.b=parseInt(m[3],16);}else if(m=c.match(/^\#([a-f\d]{1})([a-f\d]{1})([a-f\d]{1})$/i)){o.r=parseInt(m[1]+"0",16);o.g=parseInt(m[2]+"0",16);o.b=parseInt(m[3]+"0",16);}else if(m=c.match(/^rgba*\(\s*(\d+),\s*(\d+),\s*(\d+)/i)){o.r=m[1];o.g=m[2];o.b=m[3];}else if(m=c.match(/^rgba*\(\s*(\d+)\%,\s*(\d+)\%,\s*(\d+)\%/i)){o.r=Math.round(m[1]*255/100);o.g=Math.round(m[2]*255/100);o.b=Math.round(m[3]*255/100);}else{return null;}
return o;};html5jp.graph.vbar.prototype._draw_vertical_bar_square=function(ctx,x,y,h,xr,yr,color,alpha,balpha,bgradation){if(typeof(alpha)!="number"||alpha<0||alpha>1){alpha=1;}
if(typeof(balpha)!="number"||balpha<0||balpha>1){balpha=1;}
var p={f:{tl:{x:x-xr-yr,y:y-h+yr},tr:{x:x+xr-yr,y:y-h+yr},bl:{x:x-xr-yr,y:y+yr},br:{x:x+xr-yr,y:y+yr}},b:{tl:{x:x-xr+yr,y:y-h-yr},tr:{x:x+xr+yr,y:y-h-yr},bl:{x:x-xr+yr,y:y-yr},br:{x:x+xr+yr,y:y-yr}}}
ctx.save();ctx.strokeStyle="black";ctx.globalAlpha=balpha;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.f.bl.x,p.f.bl.y);ctx.lineTo(p.b.bl.x,p.b.bl.y);ctx.lineTo(p.b.br.x,p.b.br.y);ctx.stroke();ctx.beginPath();ctx.moveTo(p.b.bl.x,p.b.bl.y);ctx.lineTo(p.b.tl.x,p.b.tl.y);ctx.stroke();ctx.restore();ctx.save();ctx.fillStyle=color;ctx.globalAlpha=alpha;ctx.beginPath();ctx.moveTo(p.f.bl.x,p.f.bl.y);ctx.lineTo(p.f.tl.x,p.f.tl.y);ctx.lineTo(p.b.tl.x,p.b.tl.y);ctx.lineTo(p.b.tr.x,p.b.tr.y);ctx.lineTo(p.b.br.x,p.b.br.y);ctx.lineTo(p.f.br.x,p.f.br.y);ctx.closePath();ctx.fill();ctx.restore();ctx.save();ctx.strokeStyle="white";ctx.globalAlpha=balpha;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.f.bl.x,p.f.bl.y);ctx.lineTo(p.f.tl.x,p.f.tl.y);ctx.lineTo(p.b.tl.x,p.b.tl.y);ctx.lineTo(p.b.tr.x,p.b.tr.y);ctx.lineTo(p.b.br.x,p.b.br.y);ctx.lineTo(p.f.br.x,p.f.br.y);ctx.closePath();ctx.stroke();ctx.beginPath();ctx.moveTo(p.f.tl.x,p.f.tl.y);ctx.lineTo(p.f.tr.x,p.f.tr.y);ctx.lineTo(p.b.tr.x,p.b.tr.y);ctx.stroke();ctx.beginPath();ctx.moveTo(p.f.tr.x,p.f.tr.y);ctx.lineTo(p.f.br.x,p.f.br.y);ctx.stroke();ctx.restore();if(bgradation==true){ctx.save();var grad=ctx.createLinearGradient(p.f.tl.x,p.f.tl.y,p.f.br.x,p.f.br.y);grad.addColorStop(0,"rgba(0, 0, 0, 0.1)");grad.addColorStop(0.3,"rgba(255, 255, 255, 0.1)");grad.addColorStop(1,"rgba(0, 0, 0, 0.4)");ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(p.f.tl.x,p.f.tl.y);ctx.lineTo(p.f.tr.x,p.f.tr.y);ctx.lineTo(p.f.br.x,p.f.br.y);ctx.lineTo(p.f.bl.x,p.f.bl.y);ctx.closePath();ctx.fill();ctx.restore();ctx.save();var grad3=ctx.createLinearGradient(p.f.tr.x,p.f.tr.y,p.b.tr.x,p.f.tr.y);grad3.addColorStop(0,"rgba(0, 0, 0, 0.3)");grad3.addColorStop(1,"rgba(0, 0, 0, 0.5)");ctx.fillStyle=grad3;ctx.beginPath();ctx.moveTo(p.f.tr.x,p.f.tr.y);ctx.lineTo(p.b.tr.x,p.b.tr.y);ctx.lineTo(p.b.br.x,p.b.br.y);ctx.lineTo(p.f.br.x,p.f.br.y);ctx.closePath();ctx.fill();ctx.restore();ctx.save();var grad2=ctx.createLinearGradient(x-xr/5,y-h+yr,x+xr/5,y-h-yr);grad2.addColorStop(0,"rgba(255, 255, 255, 0.2)");grad2.addColorStop(1,"rgba(0, 0, 0, 0.1)");ctx.fillStyle=grad2;ctx.beginPath();ctx.moveTo(p.f.tl.x,p.f.tl.y);ctx.lineTo(p.f.tr.x,p.f.tr.y);ctx.lineTo(p.b.tr.x,p.b.tr.y);ctx.lineTo(p.b.tl.x,p.b.tl.y);ctx.closePath();ctx.fill();ctx.restore();}else{ctx.save();ctx.fillStyle="rgba(0,0,0,0.4)";ctx.beginPath();ctx.moveTo(p.f.tr.x,p.f.tr.y);ctx.lineTo(p.b.tr.x,p.b.tr.y);ctx.lineTo(p.b.br.x,p.b.br.y);ctx.lineTo(p.f.br.x,p.f.br.y);ctx.closePath();ctx.fill();ctx.restore();ctx.save();ctx.fillStyle="rgba(255,255,255,0.2)";ctx.beginPath();ctx.moveTo(p.f.tl.x,p.f.tl.y);ctx.lineTo(p.f.tr.x,p.f.tr.y);ctx.lineTo(p.b.tr.x,p.b.tr.y);ctx.lineTo(p.b.tl.x,p.b.tl.y);ctx.closePath();ctx.fill();ctx.restore();}};html5jp.graph.vbar.prototype._draw_vertical_bar_line=function(ctx,x,y,h,xr,color,alpha){if(typeof(alpha)!="number"||alpha<0||alpha>1){alpha=1;}
if(typeof(xr)!="number"||xr<=0){xr=0.5;}
ctx.save();ctx.strokeStyle=color;ctx.globalAlpha=alpha;ctx.lineCap="butt";ctx.lineWidth=Math.round(xr*2);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-h);ctx.stroke();ctx.restore();};html5jp.graph.vbar.prototype._draw_vertical_bar_flat=function(ctx,x,y,h,xr,color,alpha,balpha,bgradation){if(typeof(alpha)!="number"||alpha<0||alpha>1){alpha=1;}
if(typeof(balpha)!="number"||balpha<0||balpha>1){balpha=1;}
ctx.save();ctx.fillStyle=color;ctx.globalAlpha=alpha;ctx.beginPath();ctx.moveTo(x+xr,y);ctx.lineTo(x-xr,y);ctx.lineTo(x-xr,y-h);ctx.lineTo(x+xr,y-h);ctx.closePath();ctx.fill();ctx.restore();ctx.save();ctx.globalAlpha=balpha;ctx.strokeStyle="black";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x-xr,y);ctx.lineTo(x+xr,y);ctx.lineTo(x+xr,y-h);ctx.lineTo(x-xr,y-h);ctx.closePath();ctx.stroke();ctx.restore();ctx.save();ctx.lineWidth=1;ctx.globalAlpha=0.3;ctx.beginPath();ctx.strokeStyle="black";ctx.moveTo(x-xr+1,y-1);ctx.lineTo(x+xr-1,y-1);ctx.lineTo(x+xr-1,y-h+1);ctx.stroke();ctx.beginPath();ctx.strokeStyle="white";ctx.moveTo(x+xr-1,y-h+1);ctx.lineTo(x-xr+1,y-h+1);ctx.lineTo(x-xr+1,y-1);ctx.stroke();ctx.restore();if(bgradation==true){ctx.save();ctx.lineWidth=1;var grad=ctx.createLinearGradient(x-xr,y-h,x+xr,y);grad.addColorStop(0,"rgba(0, 0, 0, 0.1)");grad.addColorStop(0.3,"rgba(255, 255, 255, 0.1)");grad.addColorStop(1,"rgba(0, 0, 0, 0.4)");ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(x-xr+2,y-2);ctx.lineTo(x+xr-2,y-2);ctx.lineTo(x+xr-2,y-h+2);ctx.lineTo(x-xr+2,y-h+2);ctx.closePath();ctx.fill();ctx.restore();}};html5jp.graph.vbar.prototype._draw_vertical_bar_cylinder=function(ctx,x,y,h,xr,yr,color,alpha,balpha,bgradation){if(typeof(alpha)!="number"||alpha<0||alpha>1){alpha=1;}
if(typeof(balpha)!="number"||balpha<0||balpha>1){balpha=1;}
ctx.save();ctx.strokeStyle="black";ctx.globalAlpha=balpha;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x-xr,y);ctx.bezierCurveTo(x-xr,y-yr/2,x-xr/2,y-yr,x,y-yr);ctx.bezierCurveTo(x+xr/2,y-yr,x+xr,y-yr/2,x+xr,y);ctx.stroke();ctx.restore();ctx.save();ctx.fillStyle=color;ctx.globalAlpha=alpha;ctx.beginPath();ctx.moveTo(x-xr,y);ctx.lineTo(x-xr,y-h);ctx.bezierCurveTo(x-xr,y-h-yr/2,x-xr/2,y-h-yr,x,y-h-yr);ctx.bezierCurveTo(x+xr/2,y-h-yr,x+xr,y-h-yr/2,x+xr,y-h);ctx.lineTo(x+xr,y);ctx.bezierCurveTo(x+xr,y+yr/2,x+xr/2,y+yr,x,y+yr);ctx.bezierCurveTo(x-xr/2,y+yr,x-xr,y+yr/2,x-xr,y);ctx.fill();ctx.restore();ctx.save();ctx.strokeStyle="white";ctx.globalAlpha=balpha;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x-xr,y);ctx.bezierCurveTo(x-xr,y+yr/2,x-xr/2,y+yr,x,y+yr);ctx.bezierCurveTo(x+xr/2,y+yr,x+xr,y+yr/2,x+xr,y);ctx.stroke();ctx.beginPath();ctx.moveTo(x-xr,y);ctx.lineTo(x-xr,y-h);ctx.stroke();ctx.beginPath();ctx.moveTo(x+xr,y);ctx.lineTo(x+xr,y-h);ctx.stroke();ctx.beginPath();ctx.moveTo(x-xr,y-h);ctx.bezierCurveTo(x-xr,y-h-yr/2,x-xr/2,y-h-yr,x,y-h-yr);ctx.bezierCurveTo(x+xr/2,y-h-yr,x+xr,y-h-yr/2,x+xr,y-h);ctx.bezierCurveTo(x+xr,y-h+yr/2,x+xr/2,y-h+yr,x,y-h+yr);ctx.bezierCurveTo(x-xr/2,y-h+yr,x-xr,y-h+yr/2,x-xr,y-h);ctx.stroke();ctx.restore();if(bgradation==true){ctx.save();var grad1=ctx.createLinearGradient(x-xr,y,x+xr,y);grad1.addColorStop(0,"rgba(0, 0, 0, 0.1)");grad1.addColorStop(0.4,"rgba(255, 255, 255, 0.3)");grad1.addColorStop(1,"rgba(0, 0, 0, 0.3)");ctx.fillStyle=grad1;ctx.beginPath();ctx.moveTo(x+xr,y);ctx.bezierCurveTo(x+xr,y+yr/2,x+xr/2,y+yr,x,y+yr);ctx.bezierCurveTo(x-xr/2,y+yr,x-xr,y+yr/2,x-xr,y);ctx.lineTo(x-xr,y-h);ctx.bezierCurveTo(x-xr,y-h+yr/2,x-xr/2,y-h+yr,x,y-h+yr);ctx.bezierCurveTo(x+xr/2,y-h+yr,x+xr,y-h+yr/2,x+xr,y-h);ctx.lineTo(x+xr,y);ctx.fill();ctx.restore();ctx.save();var grad2=ctx.createLinearGradient(x-xr/5,y-h+yr,x+xr/5,y-h-yr);grad2.addColorStop(0,"rgba(255, 255, 255, 0.2)");grad2.addColorStop(1,"rgba(0, 0, 0, 0.1)");ctx.fillStyle=grad2;ctx.beginPath();ctx.moveTo(x-xr,y-h);ctx.bezierCurveTo(x-xr,y-h-yr/2,x-xr/2,y-h-yr,x,y-h-yr);ctx.bezierCurveTo(x+xr/2,y-h-yr,x+xr,y-h-yr/2,x+xr,y-h);ctx.bezierCurveTo(x+xr,y-h+yr/2,x+xr/2,y-h+yr,x,y-h+yr);ctx.bezierCurveTo(x-xr/2,y-h+yr,x-xr,y-h+yr/2,x-xr,y-h);ctx.fill();ctx.restore();}else{ctx.save();ctx.globalAlpha=0.2;ctx.fillStyle="white";ctx.beginPath();ctx.moveTo(x-xr,y-h);ctx.bezierCurveTo(x-xr,y-h-yr/2,x-xr/2,y-h-yr,x,y-h-yr);ctx.bezierCurveTo(x+xr/2,y-h-yr,x+xr,y-h-yr/2,x+xr,y-h);ctx.bezierCurveTo(x+xr,y-h+yr/2,x+xr/2,y-h+yr,x,y-h+yr);ctx.bezierCurveTo(x-xr/2,y-h+yr,x-xr,y-h+yr/2,x-xr,y-h);ctx.fill();ctx.restore();}};


//radar.js v1.0.2
if(typeof html5jp=='undefined'){html5jp=new Object();}
if(typeof html5jp.graph=='undefined'){html5jp.graph=new Object();}
html5jp.graph.radar=function(id){var elm=document.getElementById(id);if(!elm){return;}
if(!elm.nodeName.match(/^CANVAS$/i)){return;}
if(!elm.parentNode.nodeName.match(/^DIV$/i)){return;};if(!elm.getContext){return;}
this.canvas=elm;this.ctx=this.canvas.getContext('2d');this.canvas.style.margin="0";this.canvas.parentNode.style.position="relative";this.canvas.parentNode.style.padding="0";this.canvas.parentNode.style.width=this.canvas.width+"px";this.canvas.parentNode.style.height=this.canvas.height+"px";};html5jp.graph.radar.prototype.draw=function(items,inparams){if(!this.ctx){return;}
var params={aCap:[],aCapColor:"#000000",aCapFontSize:"12px",aCapFontFamily:"Arial,sans-serif",aMax:null,aMin:0,backgroundColor:"#ffffff",cBackgroundColor:"#eeeeee",cBackgroundGradation:true,chartShape:"polygon",faceColors:null,_faceColors:["rgb(24,41,206)","rgb(198,0,148)","rgb(214,0,0)","rgb(255,156,0)","rgb(33,156,0)","rgb(33,41,107)","rgb(115,0,90)","rgb(132,0,0)","rgb(165,99,0)","rgb(24,123,0)"],faceAlpha:0.1,borderAlpha:0.5,borderWidth:1,axisColor:"#aaaaaa",axisWidth:1,aLinePositions:"auto",aLineWidth:1,aLineColor:"#cccccc",sLabel:true,sLabelColor:"#000000",sLabelFontSize:"10px",sLabelFontFamily:"Arial,sans-serif",legend:true,legendFontSize:"12px",legendFontFamily:"Arial,sans-serif",legendColor:"#000000"};if(inparams&&typeof(inparams)=='object'){for(var key in inparams){if(key.match(/^_/)){continue;}
params[key]=inparams[key];}}
if(params.faceColors!=null&&params.faceColors.length>0){for(var i=0;i<params._faceColors.length;i++){var c=params.faceColors[i];var co=this._csscolor2rgb(c);if(co==null){params.faceColors[i]=params._faceColors[i];}else{params.faceColors[i]=c;}}}else{params.faceColors=params._faceColors;}
this.params=params;if(params.backgroundColor){this.ctx.beginPath();this.ctx.fillStyle=params.backgroundColor;this.ctx.fillRect(0,0,this.canvas.width,this.canvas.height);}
if(this.canvas.width/this.canvas.height<1.5||this.canvas.height<200){params.legend==false;}
var canvas_pos=this._getElementAbsPos(this.canvas);var cpos={x:this.canvas.width/2,y:this.canvas.height/2,r:Math.min(this.canvas.width,this.canvas.height)*0.75/2};if(params.legend==true){cpos.r=Math.min(this.canvas.width,this.canvas.height)*0.7/2
cpos.x=this.canvas.height*0.1+cpos.r;}
var item_num=items.length;if(item_num>10){item_num=10;}
params.itemNum=item_num;var angle_num=0;for(var i=0;i<items.length;i++){var n=items[i].length;if(angle_num<=n-1){angle_num=n-1;}}
if(angle_num<3){angle_num=3;}else if(angle_num>24){angle_num=24;}
params.angleNum=angle_num;var axis_angles=[Math.PI/2];for(var i=1;i<angle_num;i++){axis_angles.push(Math.PI/2-Math.PI*2*i/angle_num);}
this._draw_chart_shape(params,cpos,axis_angles);var max_v=null;var min_v=null;var max_n=0;for(var i=0;i<item_num;i++){var n=items[i].length;for(var j=1;j<n;j++){var v=items[i][j];if(isNaN(v)){throw new Error('Item data is invalid. : '+n);}
if(max_v==null){max_v=v;}else if(v>=max_v){max_v=v;}
if(min_v==null){min_v=v;}else if(v<=min_v){min_v=v;}}
if(n-1>=max_n){max_n=n-1;}}
if(typeof(params.aMin)!="number"){params.aMin=0;}
if(typeof(params.aMax)!="number"){params.aMax=max_v;}
if(typeof(params.aLinePositions)=="string"&&params.aLinePositions=="auto"){params.aLinePositions=this._aline_positions_auto_calc(params.aMin,params.aMax);}
this._draw_aline(params,cpos,axis_angles);this._draw_axis(params,cpos,axis_angles);this._draw_scale_label(params,cpos);for(var i=0;i<items.length;i++){this._draw_radar_chart(params,cpos,axis_angles,items[i],params.faceColors[i]);}
this._draw_caption(params,cpos,axis_angles);this._draw_legend(items,params,cpos);};html5jp.graph.radar.prototype._aline_positions_auto_calc=function(min,max){var range=max-min;var power10=Math.floor(Math.log(range)/Math.log(10));var unit=Math.pow(10,power10);if((Math.log(range)/Math.log(10))%1==0){unit=unit/10;}
var keta_age=1;if(unit<1){keta_age+=Math.abs(power10);}
var p=Math.pow(10,keta_age);range=range*p;unit=unit*p;min=min*p;max=max*p;var array=[min];var unum=range/unit;if(unum>5){unit=unit*2;}else if(unum<=2){unit=unit*3/10}
var i=1;while(min+unit*i<=max){array.push(min+unit*i);i++;}
for(var i=0;i<array.length;i++){array[i]=array[i]/p;}
return array;};html5jp.graph.radar.prototype._draw_legend=function(items,params,cpos){if(params.legend!=true){return;}
var s=this._getTextBoxSize('TEST',params.legendFontSize,params.legendFontFamily);var lpos={x:Math.round(cpos.x+cpos.r+this.canvas.width*0.15),y:Math.round((this.canvas.height-(s.h*params.itemNum+s.h*0.2*(params.itemNum-1)))/2),h:s.h};lpos.cx=lpos.x+Math.round(lpos.h*1.5);lpos.cw=this.canvas.width-lpos.cx;for(var i=0;i<params.itemNum;i++){this._drawText(lpos.cx,lpos.y,items[i][0],params.legendFontSize,params.legendFontFamily,params.legendColor);this._make_path_legend_mark(lpos.x,lpos.y,s.h,s.h);this.ctx.fillStyle=params.cBackgroundColor;this.ctx.fill();this.ctx.fillStyle=params.faceColors[i];this.ctx.globalAlpha=params.faceAlpha;this.ctx.fill();this.ctx.strokeStyle=params.faceColors[i];this.ctx.globalAlpha=params.borderAlpha;this.ctx.stroke();lpos.y=lpos.y+lpos.h*1.2;}};html5jp.graph.radar.prototype._make_path_legend_mark=function(x,y,w,h){this.ctx.beginPath();this.ctx.moveTo(x,y);this.ctx.lineTo(x+w,y);this.ctx.lineTo(x+w,y+h);this.ctx.lineTo(x,y+h);this.ctx.closePath();};html5jp.graph.radar.prototype._draw_caption=function(params,cpos,axis_angles){if(typeof(params.aCap)!="object"||params.aCap.length<1){return;}
var n=params.aCap.length;if(n>params.angleNum){n=params.angleNum;}
for(var i=0;i<n;i++){var text=params.aCap[i];var s=this._getTextBoxSize(text,params.aCapFontSize,params.aCapFontFamily);var ang=axis_angles[i];var x=cpos.x+cpos.r*1.15*Math.cos(ang)-s.w/2;var y=cpos.y-cpos.r*1.15*Math.sin(ang)-s.h/2;if(x<this.canvas.width*0.02){x=this.canvas.width*0.02;}
if(x+s.w>this.canvas.width*0.98){x=this.canvas.width*0.98-s.w;}
if(y<this.canvas.height*0.02){y=this.canvas.height*0.02;}
if(y+s.h>this.canvas.height*0.98){y=this.canvas.height*0.98-s.h;}
x=Math.round(x);y=Math.round(y);this._drawText(x,y,text,params.aCapFontSize,params.aCapFontFamily,params.aCapColor);}};html5jp.graph.radar.prototype._draw_scale_label=function(params,cpos){if(params.sLabel!=true){return;}
if(typeof(params.aLinePositions)!="object"||params.aLinePositions.length<1){return;}
for(var i=0;i<params.aLinePositions.length;i++){if(typeof(params.aLinePositions[i])!="number"){continue;}
if(params.aLinePositions[i]<params.aMin){continue;}
var text=params.aLinePositions[i].toString();var s=this._getTextBoxSize(text,params.sLabelFontSize,params.sLabelFontFamily);var x=Math.round(cpos.x-s.w-3);var y=Math.round(cpos.y-((params.aLinePositions[i]-params.aMin)*cpos.r/(params.aMax-params.aMin))-(s.h/2));this._drawText(x,y,text,params.sLabelFontSize,params.sLabelFontFamily,params.sLabelColor);}};html5jp.graph.radar.prototype._draw_radar_chart=function(params,cpos,axis_angles,values,color){this._make_path_for_radar_chart(params,cpos,axis_angles,values);this.ctx.globalAlpha=params.faceAlpha;this.ctx.fillStyle=color;this.ctx.fill();this.ctx.globalAlpha=params.borderAlpha;this.ctx.lineWidth=params.borderWidth;this.ctx.strokeStyle=color;this.ctx.stroke();this.ctx.globalAlpha=1;};html5jp.graph.radar.prototype._make_path_for_radar_chart=function(params,cpos,axis_angles,values){var r0=0;if(typeof(values[1])=="number"){r0=cpos.r*(values[1]-params.aMin)/(params.aMax-params.aMin);if(r0<0){r0=0;}}
this.ctx.beginPath();this.ctx.moveTo(Math.round(cpos.x+r0*Math.cos(axis_angles[0])),Math.round(cpos.y-r0*Math.sin(axis_angles[0])));for(var i=1;i<axis_angles.length;i++){var r=0;if(typeof(values[i+1])=="number"){r=cpos.r*(values[i+1]-params.aMin)/(params.aMax-params.aMin);if(r<0){r=0;}}
this.ctx.lineTo(Math.round(cpos.x+r*Math.cos(axis_angles[i])),Math.round(cpos.y-r*Math.sin(axis_angles[i])));}
this.ctx.closePath();};html5jp.graph.radar.prototype._draw_axis=function(params,cpos,axis_angles){if(typeof(params.axisWidth)!="number"||params.axisWidth<=0){return;}
for(var i=0;i<axis_angles.length;i++){this.ctx.beginPath();this.ctx.lineWidth=params.axisWidth;this.ctx.strokeStyle=params.axisColor;this.ctx.moveTo(cpos.x,cpos.y);this.ctx.lineTo(Math.round(cpos.x+cpos.r*Math.cos(axis_angles[i])),Math.round(cpos.y-cpos.r*Math.sin(axis_angles[i])));this.ctx.stroke();}};html5jp.graph.radar.prototype._draw_aline=function(params,cpos,axis_angles){if(typeof(params.aLineWidth)!="number"||params.aLineWidth<=0){return;}
if(typeof(params.aLinePositions)!="object"||params.aLinePositions.length<1){return;}
for(var i=0;i<params.aLinePositions.length;i++){if(params.aLinePositions[i]<params.aMin){continue;}
var r=cpos.r*(params.aLinePositions[i]-params.aMin)/(params.aMax-params.aMin);if(r<=0){continue;}
this.ctx.beginPath();this.ctx.lineWidth=params.aLineWidth;this.ctx.strokeStyle=params.aLineColor;if(params.chartShape=="polygon"){this.ctx.moveTo(Math.round(cpos.x+r*Math.cos(axis_angles[0])),Math.round(cpos.y-r*Math.sin(axis_angles[0])));for(var j=1;j<axis_angles.length;j++){this.ctx.lineTo(Math.round(cpos.x+r*Math.cos(axis_angles[j])),Math.round(cpos.y-r*Math.sin(axis_angles[j])));}
this.ctx.closePath();}else if(params.chartShape=="circle"){this.ctx.arc(cpos.x,cpos.y,r,0,Math.PI*2,false);}else{throw new Error('Option parameter [chartChape] is invalid. : '+params.chartShape);}
this.ctx.stroke();}};html5jp.graph.radar.prototype._draw_chart_shape=function(params,cpos,axis_angles){this._make_path_chart_shape(params,cpos,axis_angles);this.ctx.fillStyle=params.cBackgroundColor;this.ctx.fill();if(params.cBackgroundGradation==true&&!document.uniqueID){this._make_path_chart_shape(params,cpos,axis_angles);var radgrad=this.ctx.createRadialGradient(cpos.x,cpos.y,0,cpos.x,cpos.y,cpos.r);radgrad.addColorStop(0,"rgba(0,0,0,0)");radgrad.addColorStop(0.8,"rgba(0,0,0,0.01)");radgrad.addColorStop(1,"rgba(0,0,0,0.1)");this.ctx.fillStyle=radgrad;this.ctx.fill();}};html5jp.graph.radar.prototype._make_path_chart_shape=function(params,cpos,axis_angles){this.ctx.beginPath();if(params.chartShape=="circle"){this.ctx.arc(cpos.x,cpos.y,cpos.r,0,Math.PI*2,false);}else if(params.chartShape=="polygon"){this.ctx.moveTo(cpos.x,cpos.y-cpos.r);for(var i=0;i<axis_angles.length;i++){var edge_x=Math.round(cpos.x+cpos.r*Math.cos(axis_angles[i]));var edge_y=Math.round(cpos.y-cpos.r*Math.sin(axis_angles[i]));this.ctx.lineTo(edge_x,edge_y);}
this.ctx.closePath();}else{throw new Error('Option parameter [chartChape] is invalid. : '+params.chartShape);}};html5jp.graph.radar.prototype._drawText=function(x,y,text,font_size,font_family,color){var div=document.createElement('DIV');div.appendChild(document.createTextNode(text));div.style.fontSize=font_size;div.style.fontFamily=font_family;div.style.color=color;div.style.margin="0";div.style.padding="0";div.style.position="absolute";div.style.left=x.toString()+"px";div.style.top=y.toString()+"px";this.canvas.parentNode.appendChild(div);}
html5jp.graph.radar.prototype._getTextBoxSize=function(text,font_size,font_family){var tmpdiv=document.createElement('DIV');tmpdiv.appendChild(document.createTextNode(text));tmpdiv.style.fontSize=font_size;tmpdiv.style.fontFamily=font_family;tmpdiv.style.margin="0";tmpdiv.style.padding="0";tmpdiv.style.visible="hidden";tmpdiv.style.position="absolute";tmpdiv.style.left="0px";tmpdiv.style.top="0px";this.canvas.parentNode.appendChild(tmpdiv);var o={w:tmpdiv.offsetWidth,h:tmpdiv.offsetHeight};tmpdiv.parentNode.removeChild(tmpdiv);return o;}
html5jp.graph.radar.prototype._getElementAbsPos=function(elm){var obj=new Object();obj.x=elm.offsetLeft;obj.y=elm.offsetTop;while(elm.offsetParent){elm=elm.offsetParent;obj.x+=elm.offsetLeft;obj.y+=elm.offsetTop;}
return obj;};html5jp.graph.radar.prototype._csscolor2rgb=function(c){if(!c){return null;}
var color_map={black:"#000000",gray:"#808080",silver:"#c0c0c0",white:"#ffffff",maroon:"#800000",red:"#ff0000",purple:"#800080",fuchsia:"#ff00ff",green:"#008000",lime:"#00FF00",olive:"#808000",yellow:"#FFFF00",navy:"#000080",blue:"#0000FF",teal:"#008080",aqua:"#00FFFF"};c=c.toLowerCase();var o=new Object();if(c.match(/^[a-zA-Z]+$/)&&color_map[c]){c=color_map[c];}
var m=null;if(m=c.match(/^\#([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i)){o.r=parseInt(m[1],16);o.g=parseInt(m[2],16);o.b=parseInt(m[3],16);}else if(m=c.match(/^\#([a-f\d]{1})([a-f\d]{1})([a-f\d]{1})$/i)){o.r=parseInt(m[1]+"0",16);o.g=parseInt(m[2]+"0",16);o.b=parseInt(m[3]+"0",16);}else if(m=c.match(/^rgba*\(\s*(\d+),\s*(\d+),\s*(\d+)/i)){o.r=m[1];o.g=m[2];o.b=m[3];}else if(m=c.match(/^rgba*\(\s*(\d+)\%,\s*(\d+)\%,\s*(\d+)\%/i)){o.r=Math.round(m[1]*255/100);o.g=Math.round(m[2]*255/100);o.b=Math.round(m[3]*255/100);}else{return null;}
return o;};